language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

r_github_packages:
    - jimhester/covr

before_install:
    - Rscript -e 'install.packages("grid", lib="/home/travis/R-bin/lib/R/library/")'

after_success:
    - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always
